version: 1.0
provider:
  name: openfaas
  gateway: https://api.chromascope.io
functions:
  test-auth-endpoints:
    lang: node10-express-service
    handler: ./api
    image: bloom510/test-faas-api:latest
